### PR TITLE
Geo positional filter.

### PR DESCRIPTION
**Pull request by DmRomantsov**
Filters with geo-coordinates. It determines whether a point is in the square with center (latitude, longitude) and side = 2*distance.

Usage:
 @Spec(params = {"latitude", "longitude","distance"},
                    path = "latitude;longitude", spec = GeoPosition.class)

P.S: thanks for your work! It's very helpful librar

### CODE REVIEW

**Comment by tkaczmarzyk** [comment]
Thank you for your contribution.
It's an interesting case: for the first time we need to match against more than 1 path. I think the API of `@Spec` should be changed to support it, so using the trick with ";" is no needed. So I think the plan would be to change the type of `Spec.path` from `String` to `String[]`. Does it make sense? If you feel like doing it, feel free to update your PR, otherwise I'll do it next week.

**Comment by DmRomantsov** [comment]
Main work are done, but there ara some failed test, I'll fix it next week.

**Comment by tkaczmarzyk** [comment]
I think that the failing tests will work once equals/hashcode of `PathSpecification` is re-generated (since path is now an array, `Arrays.equals` and `Arrays.hashCode` must be used to properly deal with this field.

Also: maybe it would be a good idea to pass string "allowNull" instead of "true" and to allow it at any position of the config array? It would for sure complicate parsing, but maybe would be more user friendly? What do you think?

**Comment by DmRomantsov** [comment]
Yes, I think it's realy match more better for users. I'll change that, but I need some time for this.

**Comment by tkaczmarzyk** [comment]
I'm closing this due to inactivity. Feel free to reopen when you have time to support it...

**Pull request closed without merging**
