### PR TITLE
Add GreaterThan, LessThan, GreaterThanOrEqual, and LessThanOrEqual Sp…

### PR DESCRIPTION
**Pull request by tpdi**
…ecifications. Note, comparisons on floats and booleans will depend on the underlying database.

Also added an @Ignored @Test to EqualTest demonstrating that equality comparison of floats fails on the test database.

### CODE REVIEW

**Comment by tkaczmarzyk** [comment]
Great stuff, thank you. Do you think `ComparableEqual` is needed?

**Comment by tpdi** [comment]
Thank you for the library, it has been very useful for me on two projects.

No, |ComparableEqual| is cruft. My mistake.

I initially tested by naming it Equal, replacing your Equal, and running
your EqualTest (all of which passed). However, I don't want to replace
your Equal, because |ComparableEqual| needs its values to be Comparable,
which is an unnecessary constraint and might break existing code (though
I think everything your converter converts to is Comparable, so maybe
there is no chance of breakage).

I'm a bit surprised you hadn't already added these Specs -- was there a
reason you didn't?

And as long as I have your attention: I successfully used Spec
interfaces in one project, but in another they infinitely recurse,
calling the Spec interface's toString() of all things. Any idea why?

Thanks,
Tom

**Comment by tkaczmarzyk** [comment]
1. OK, I'll remove `ComparableEqual`, let's stick with the basic `Equal` for now. I'll release new version today evening (CEST)
2. There was no specific reason for not having these Specs (other than a looong TODO list ;) )
3. I had infinite recursion issue reported once, but couldn't reproduce. I'll take another look, now I know it's in `toString`, thanks. If you have a test case/example of this failure, it would be of great help, but I'll investigate anyway.

**Comment by tpdi** [comment]
I can easily give you a test case, but it's part of a project for a
client, so let me first remove anything identifiable.

I'd also like to do a little cleanup -- I probably pushed prematurely.
Let me try to get a new commit, and a recursion test case, to you within
24 hours.

**Comment by tkaczmarzyk** [comment]
Sure, thanks!

**Pull request merged**
